name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: arielaman/flask-app
      DOCKER_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker containers
      run: docker-compose up -d

    - name: Wait for containers to be ready
      run: sleep 60

    - name: Print directory contents inside flask-app container
      run: |
        docker-compose exec flask-app ls -R /app

    - name: Print directory contents inside score-app container
      run: |
        docker-compose exec score-app ls -R /app

    - name: Run tests inside flask-app container
      run: |
        docker-compose exec flask-app python /app/tests/e2e.py

    - name: Stop and remove containers
      run: docker-compose down

    - name: Push Docker images to DockerHub
      run: |
        docker tag flask-app:latest $DOCKER_IMAGE:$DOCKER_TAG
        docker push $DOCKER_IMAGE:$DOCKER_TAG
        docker tag score-app:latest $DOCKER_IMAGE:scores
        docker push $DOCKER_IMAGE:scores
